name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title-check:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure types according to conventional commits
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Require a scope (optional, remove if you don't want to enforce scopes)
          requireScope: false
          # Configure subject pattern (default: require lowercase)
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            must start with a lowercase character.

  build-and-test:
    name: Build and Test
    runs-on: macos-14  # macOS 14 for backward compatibility (has Xcode 15.4 default, supports back to 15.0.1)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Restore Swift Package Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Project
        run: |
          xcodebuild clean build \
            -project Kiwings.xcodeproj \
            -scheme Kiwings \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Run Tests
        run: |
          xcodebuild test \
            -project Kiwings.xcodeproj \
            -scheme Kiwings \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
        continue-on-error: true

      - name: Archive build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ~/Library/Logs/DiagnosticReports
            DerivedData/Logs
